apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-task-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brain-task
  template:
    metadata:
      labels:
        app: brain-task
    spec:
      containers:
        - name: brain-task
          image: 304230205204.dkr.ecr.ap-south-1.amazonaws.com/brain-task:latest
          ports:
            - containerPort: 3000